export { default as discordLogo } from "./discord.png";
export { default as facebookLogo } from "./facebook.png";
export { default as instagramLogo } from "./instagram.png";
export { default as redditLogo } from "./reddit.png";
export { default as telegramLogo } from "./telegram.png";
export { default as whatsappLogo } from "./discord.png";
export { default as xLogo } from "./x.png";
export { default as youtubeLogo } from "./youtube.png";
export { default as solLogo } from "./solana-outline.png";
